use std::fmt::{self, Display, Formatter};

use crate::{backend::StableConnectionId, stream::StreamId};
use bytes::Bytes;

/// Events, generated by a QUIC backend.
#[derive(Debug, Default)]
pub struct BackendEvents<CId: StableConnectionId> {
    events: Vec<Event<CId>>,
}

impl<CId: StableConnectionId> BackendEvents<CId> {
    #[inline]
    pub fn new() -> Self {
        Self { events: Vec::new() }
    }

    /// Consume events.
    #[inline]
    pub(crate) fn consume<F>(&mut self, mut func: F)
    where
        F: FnMut(Event<CId>),
    {
        while let Some(event) = self.events.pop() {
            func(event);
        }
    }


    /// Add a new event.
    ///
    /// Can be any of these:
    /// - [ConnectionEvent].
    /// - [StreamEvent].
    /// - [DatagramEvent].
    #[inline]
    pub fn push<E: BackendEvent<CId>>(&mut self, event: E) {
        self.events.push(event.into_event())
    }

    /// Add new events.
    ///
    /// Can be any of these:
    /// - [ConnectionEvent].
    /// - [StreamEvent].
    /// - [DatagramEvent].
    #[inline]
    pub fn extend<E, I>(&mut self, events: I)
    where
        E: BackendEvent<CId>,
        I: IntoIterator<Item = E>,
    {
        self.events
            .extend(events.into_iter().map(BackendEvent::into_event))
    }
}


/// A QUIC connection related event.
#[derive(Debug, Clone)]
pub enum ConnectionEvent<CId: StableConnectionId> {
    /// A new connection is created.
    ///
    /// It may be in any state: from `Initial` to `Handshake`,
    /// until it's established ([Active](Self::Active)).
    New { connection_id: CId, is_server: bool },

    /// Connection is fully established.
    Established(CId),

    /// Application may open a new stream of certain directionality.
    StreamsAvailable {
        connection_id: CId,

        /// Is this a unidirectional or bidirectional stream limit.
        is_bidirectional: bool,
    },

    /// Connection is draining or closed
    /// due to an application or transport error.
    Closed {
        connection_id: CId,

        /// Code the connection was closed with.
        code: u64,

        /// Close reason in UTF-8.
        reason: Bytes,

        /// Is this an application or transport close code.
        is_application: bool,

        /// Is the initiator our application, or the peer.
        is_local: bool,
    },

    /// Connection is halted and dropped due to an unknown version error.
    ///
    /// No further communication is possible afterwards on this connection.
    Halted { connection_id: CId, kind: HaltKind },
}

impl<CId: StableConnectionId> ConnectionEvent<CId> {
    pub fn connection_id(&self) -> CId {
        match self {
            Self::New { connection_id, .. } => connection_id.clone(),
            Self::Established(id) => id.clone(),
            Self::StreamsAvailable { connection_id, .. } => connection_id.clone(),
            Self::Closed { connection_id, .. } => connection_id.clone(),
            Self::Halted { connection_id, .. } => connection_id.clone(),
        }
    }
}


/// A QUIC stream related event.
#[derive(Debug, Clone)]
pub enum StreamEvent<CId: StableConnectionId> {
    /// There is a new stream; Or an existing stream has new data to read, or capacity to write.
    ///
    /// This event is produced only if an application
    /// read all available data, or hit writing limits previously.
    Available(CId, StreamId),

    /// Stream direction is terminated with a `RESET_STREAM(u64)` or `STOP_SENDING(u64)` frame.
    Reset(CId, StreamId, u64),
}

impl<CId: StableConnectionId> StreamEvent<CId> {
    pub fn connection_id(&self) -> CId {
        match self {
            Self::Available(id, _) => id.clone(),
            Self::Reset(id, _, _) => id.clone(),
        }
    }

    pub fn stream_id(&self) -> StreamId {
        match self {
            Self::Available(_, id) => *id,
            Self::Reset(_, id, _) => *id,
        }
    }
}


/// A QUIC datagram related event.
#[derive(Debug, Clone)]
pub enum DatagramEvent<CId: StableConnectionId> {
    /// Incoming datagram direction has new data to read.
    ///
    /// This event is produced only if an application
    /// read all available data previously.
    InAvailable(CId),

    /// Outgoing datagram direction is unblocked, and may be written to again.
    ///
    /// This event is produced only if an application
    /// hit writing limits previously.
    OutAvailable(CId),

    /// Outgoing datagram direction has a new updated maximum for the datagram size.
    OutNewSize(CId, u16),
}

impl<CId: StableConnectionId> DatagramEvent<CId> {
    pub fn connection_id(&self) -> CId {
        match self {
            Self::InAvailable(id) => id.clone(),
            Self::OutAvailable(id) => id.clone(),
            Self::OutNewSize(id, _) => id.clone(),
        }
    }
}


/// A QUIC connection is halted and dropped due to an error.
///
/// No further communication is possible afterwards on this connection.
#[derive(Debug, Clone)]
pub enum HaltKind {
    /// Peer's QUIC version is unsupported.
    UnknownVersion,

    /// Connection is timed out.
    Timeout,

    /// Connection migration failed.
    MigrationFailed,

    /// Connection is closed by peer's stateless reset.
    StatelessReset,

    /// Connection is closed by an unknown error.
    ///
    /// Reason is attached in the `Bytes` field.
    Error(Bytes),
}

impl Display for HaltKind {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match self {
            Self::UnknownVersion => write!(f, "unknown version"),
            Self::Timeout => write!(f, "timeout"),
            Self::MigrationFailed => write!(f, "migration failed"),
            Self::StatelessReset => write!(f, "stateless reset"),
            Self::Error(e) => write!(f, "{}", String::from_utf8_lossy(e)),
        }
    }
}


/// An event, encapsulates
/// - [ConnectionEvent].
/// - [StreamEvent].
/// - [DatagramEvent].
#[derive(Debug, Clone)]
pub(crate) enum Event<CId: StableConnectionId> {
    Connection(ConnectionEvent<CId>),
    Stream(StreamEvent<CId>),
    Datagram(DatagramEvent<CId>),
}

trait BackendEvent<CId: StableConnectionId> {
    /// Converts `self` into `Event` enum.
    fn into_event(self) -> Event<CId>;
}

impl<CId: StableConnectionId> BackendEvent<CId> for ConnectionEvent<CId> {
    fn into_event(self) -> Event<CId> {
        Event::Connection(self)
    }
}

impl<CId: StableConnectionId> BackendEvent<CId> for StreamEvent<CId> {
    fn into_event(self) -> Event<CId> {
        Event::Stream(self)
    }
}

impl<CId: StableConnectionId> BackendEvent<CId> for DatagramEvent<CId> {
    fn into_event(self) -> Event<CId> {
        Event::Datagram(self)
    }
}

impl<CId: StableConnectionId> BackendEvent<CId> for Event<CId> {
    fn into_event(self) -> Event<CId> {
        self
    }
}
