use crate::{
    backend::quiche::{Connection, ConnectionKey},
    util::{TimerKey, TimerTick, WheelTimer},
};
use std::time::{Duration, Instant, SystemTime};

pub(super) struct Time {
    /// Timer to schedule and poll events.
    timer: WheelTimer<Option<TimerEvent>>,

    /// Fired events that are ready to be handled.
    fired_events: Vec<TimerTick<Option<TimerEvent>>>,

    /// Current monotonical time.
    clock_mono: Instant,

    /// Current system time.
    clock_sys: SystemTime,
}

impl Time {
    pub fn new() -> Self {
        let clock_mono = Instant::now();
        let clock_sys = SystemTime::now();

        let fired_events = Vec::new();
        let timer = WheelTimer::new(
            Duration::from_millis(1),
            Duration::from_millis(64),
            clock_mono,
        );

        Self {
            timer,
            fired_events,
            clock_mono,
            clock_sys,
        }
    }


    /// Schedules an event to fire at the specified time.
    #[inline]
    pub fn schedule(&mut self, event: TimerEvent, at: Instant) -> TimerKey {
        self.timer.schedule(Some(event), at, self.clock_mono)
    }

    /// Cancels a previously scheduled event and replaces it with a new one.
    pub fn reschedule(
        &mut self,
        event: TimerEvent,
        at: Instant,
        mut previous_key: Option<TimerKey>,
    ) -> TimerKey {
        if let Some(key) = previous_key.take() {
            self.timer.cancel(key);
        }

        self.schedule(event, at)
    }


    /// Cancels an event associated with the specified `key`.
    pub fn cancel(&mut self, key: TimerKey) {
        self.timer.cancel(key);
    }

    /// Cancels all events related to this connection.
    pub fn cancel_all(&mut self, connection: &mut Connection) {
        let keys = [
            connection.pop_timer_key(TimerKind::Pacer),
            connection.pop_timer_key(TimerKind::QuicheTimeout),
            connection.pop_timer_key(TimerKind::EstablishTimeout),
        ];

        for key in keys.into_iter().flatten() {
            self.timer.cancel(key);
        }
    }


    /// Ticks, storing all fired events.
    /// In case of time-lag, previous events are handled too.
    ///
    /// Fired events can be retrived via [`fired_events()`][Self::fired_events].
    ///
    /// Returns the instant at which this method should be called again,
    /// and whether there are pending [`fired_events()`][Self::fired_events] to be handled.
    pub fn tick(&mut self) -> (Instant, bool) {
        let next_tick_instant = self.timer.progress(&mut self.fired_events, self.clock_mono);
        (next_tick_instant, !self.fired_events.is_empty())
    }

    /// Returns all fired events, that are ready to be handled.
    pub fn fired_events(&mut self) -> &mut Vec<TimerTick<Option<TimerEvent>>> {
        &mut self.fired_events
    }


    /// Updates internal clocks.
    pub fn update_clock(&mut self) {
        self.clock_mono = Instant::now();
        self.clock_sys = SystemTime::now();
    }

    /// Returns current monotonical time.
    pub fn now_mono(&self) -> Instant {
        self.clock_mono
    }

    /// Returns current system time.
    pub fn now_sys(&self) -> SystemTime {
        self.clock_sys
    }
}


#[derive(Debug, Copy, Clone)]
pub(super) struct TimerEvent {
    pub connection_key: ConnectionKey,
    pub kind: TimerKind,
}

#[derive(Debug, Copy, Clone)]
pub(super) enum TimerKind {
    /// Pacing algorithm determined to make a delay
    /// between packets to be sent.
    Pacer,

    /// Timeout generated by Quiche.
    QuicheTimeout,

    /// Connection establishment (full handshake phase) timeout.
    EstablishTimeout,
}
