use crate::util::KeyStore;
use digest::{KeyInit, Mac};
use subtle::ConstantTimeEq;
use typenum::Unsigned;

/// HMAC, provides authentication and verification methods
/// and allows manual key rotation using [KeyConsumer].
pub struct Hmac<M, K> {
    macs: Vec<M>,
    key_store: K,
    revision: u64,
}

impl<M, K> Hmac<M, K>
where
    M: KeyInit + Mac + Clone,
    K: KeyStore<KeySize = M::KeySize>,
{
    /// Creates a new hmac instance.
    pub fn new(key_store: K) -> Self {
        let mut this = Self {
            macs: Vec::new(),
            key_store,
            revision: 0,
        };

        this.update_keys();
        this
    }

    /// Computes HMAC based on the provided data.
    pub fn compute(&mut self, data: &[u8], out: &mut Vec<u8>) {
        self.compare_and_update_keys();

        let mut provider = self.macs[0].clone();
        provider.update(data);

        let output = provider.finalize();
        out.extend_from_slice(output.as_bytes().as_ref());
    }

    /// Returns `true` if `data` is authentic,
    /// and the `expected_hmac` was previously generated using one of the present keys.
    pub fn verify(&mut self, data: &[u8], expected_hmac: &[u8]) -> bool {
        if expected_hmac.len() != <M::OutputSize as Unsigned>::USIZE {
            return false;
        }

        self.verify_fn(data, expected_hmac, |hmac| hmac)
    }

    /// Returns `true` if `data` is authentic.
    ///
    /// It takes a `transform` function,
    /// that converts an actual hmacs (generated by the present keys) into a slice,
    /// that should have the same format as the `expected_hmac`.
    ///
    /// Comparison is made between the resulting slice and `expected_hmac`.
    pub fn verify_fn<F>(&mut self, data: &[u8], expected_hmac: &[u8], mut transform: F) -> bool
    where
        F: FnMut(&[u8]) -> &[u8],
    {
        self.compare_and_update_keys();

        for mut provider in self.macs.iter().cloned() {
            provider.update(data);

            let output = provider.finalize();
            let slice = transform(output.as_bytes().as_ref());

            if slice.ct_eq(expected_hmac).into() {
                return true;
            }
        }

        false
    }


    fn compare_and_update_keys(&mut self) {
        if self.revision != self.key_store.revision() {
            self.update_keys();
        }
    }

    #[rustfmt::skip]
    fn update_keys(&mut self) {
        self.macs.clear();
        self.macs.push(M::new(self.key_store.active()));
        self.macs.extend(self.key_store.passive().map(M::new));
        self.revision = self.key_store.revision();
    }
}
