use crate::util::KeyConsumer;
use digest::{KeyInit, Mac, array::Array};
use std::{any::type_name, marker::PhantomData};
use subtle::ConstantTimeEq;
use typenum::Unsigned;
use zeroize::Zeroize;

/// HMAC, provides authentication and verification methods
/// and allows manual key rotation using [KeyConsumer].
pub struct Hmac<M, K> {
    keys: Vec<u8>,
    key_consumer: K,
    revision: u64,
    _phantom: PhantomData<M>,
}

impl<M, K> Hmac<M, K>
where
    M: KeyInit + Mac,
    K: KeyConsumer,
{
    /// Creates a new hmac instance.
    pub fn new(key_consumer: K) -> Self {
        let mut this = Self {
            keys: Vec::new(),
            key_consumer,
            revision: 0,
            _phantom: PhantomData,
        };

        this.update_keys();
        this
    }

    /// Computes HMAC based on the provided data.
    pub fn compute(&mut self, data: &[u8], out: &mut Vec<u8>) {
        self.compare_and_update_keys();

        let mut provider = self.active_provider();
        provider.update(data);

        let output = provider.finalize();
        out.extend_from_slice(output.as_bytes().as_ref());
    }

    /// Returns `true` if `data` is authentic,
    /// and the `expected_hmac` was previously generated using one of the present keys.
    pub fn verify(&mut self, data: &[u8], expected_hmac: &[u8]) -> bool {
        if expected_hmac.len() != <M::OutputSize as Unsigned>::USIZE {
            return false;
        }

        self.verify_fn(data, expected_hmac, |hmac| hmac)
    }

    /// Returns `true` if `data` is authentic.
    ///
    /// It takes a `transform` function,
    /// that converts an actual hmacs (generated by the present keys) into a slice,
    /// that should have the same format as the `expected_hmac`.
    ///
    /// Comparison is made between the resulting slice and `expected_hmac`.
    pub fn verify_fn<F>(&mut self, data: &[u8], expected_hmac: &[u8], mut transform: F) -> bool
    where
        F: FnMut(&[u8]) -> &[u8],
    {
        self.compare_and_update_keys();

        for mut provider in self.all_providers() {
            provider.update(data);

            let output = provider.finalize();
            let slice = transform(output.as_bytes().as_ref());

            if slice.ct_eq(expected_hmac).into() {
                return true;
            }
        }

        false
    }


    fn compare_and_update_keys(&mut self) {
        if self.revision != self.key_consumer.revision() {
            self.update_keys();
        }
    }

    #[rustfmt::skip]
    fn update_keys(&mut self) {
        let verify_key = |key: &[u8]| {
            if key.len() != M::KeySize::USIZE {
                panic!("HMAC {} key must be {} bytes long", type_name::<M>(), M::KeySize::USIZE);
            }
        };

        self.keys.zeroize();
        self.keys.clear();

        self.keys.extend_from_slice({
            let key = self.key_consumer.active();
            verify_key(key);
            key
        });

        for key in self.key_consumer.passive() {
            verify_key(key);
            self.keys.extend_from_slice(key);
        }

        self.revision = self.key_consumer.revision();
    }


    fn active_provider(&self) -> M {
        let key = Array::<u8, M::KeySize>::try_from(&self.keys[0..M::KeySize::USIZE])
            .expect("keys chunk should have the right size");

        Self::key_to_provider(&key)
    }

    fn all_providers(&self) -> impl Iterator<Item = M> + '_ {
        self.keys
            .chunks_exact(M::KeySize::USIZE)
            .map(|chunk| {
                Array::<u8, M::KeySize>::try_from(chunk).expect("chunk should have the right size")
            })
            .map(|array| Self::key_to_provider(&array))
    }

    fn key_to_provider(key: &Array<u8, M::KeySize>) -> M {
        <M as KeyInit>::new(key)
    }
}

impl<M, K> Drop for Hmac<M, K> {
    fn drop(&mut self) {
        self.keys.zeroize();
    }
}
